name: CoRaCMG
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - torch
  - transformers
  - scikit-learn
  - tqdm
  - jina
  - sentence-transformers
  - fire
  - pip
  - pip:
      - evaluate
      - datasets
